@host = http://localhost:3000

POST {{host}}/users
Content-Type: application/json

{
    "first_name": "Buhari",
    "last_name": "Muhammed"
}

###

GET {{host}}/users
Content-Type: application/json

