@host = https://z1brh9zbgk.execute-api.af-south-1.amazonaws.com

POST {{host}}/users
Content-Type: application/json

{
    "first_name": "Waheed",
    "last_name": "Ismaila"
}

###

GET {{host}}/users
Content-Type: application/json

